from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Callable, List, Optional
import os
import re
import shutil
import subprocess
import time
import uuid

from cancel import CancelContext, CancelledError
from manifest import write_manifest
from project_paths import pdf_output_root, repo_root

@dataclass
class PdfPage:
    page: int
    png_path: str
    width: int
    height: int


@dataclass
class PdfIngestResult:
    doc_id: str
    output_dir: str
    manifest_path: str
    pages: List[PdfPage]


BEIJING_TZ = timezone(timedelta(hours=8))


def _now() -> datetime:
    return datetime.now(BEIJING_TZ)


def _now_iso() -> str:
    return _now().isoformat()


def _stamp(fmt: str = "%Y%m%d-%H%M%S") -> str:
    return _now().strftime(fmt)


def _generate_doc_id(stem: str) -> str:
    ts = _stamp()
    short_id = uuid.uuid4().hex[:6]
    safe = re.sub(r"[^a-zA-Z0-9_-]+", "_", stem).strip("_")
    return f"{safe}-{ts}-{short_id}"


def _png_size(path: Path) -> tuple[int, int]:
    with path.open("rb") as fh:
        header = fh.read(24)
    if len(header) < 24 or header[:8] != b"\x89PNG\r\n\x1a\n":
        return (0, 0)
    width = int.from_bytes(header[16:20], "big")
    height = int.from_bytes(header[20:24], "big")
    return width, height


def _ensure_pdftoppm() -> str:
    for path in os.environ.get("PATH", "").split(os.pathsep):
        candidate = Path(path) / "pdftoppm"
        if candidate.exists():
            return str(candidate)
        candidate = Path(path) / "pdftoppm.exe"
        if candidate.exists():
            return str(candidate)
    return ""


def _page_sort_key(path: Path) -> int:
    match = re.search(r"-(\d+)$", path.stem)
    return int(match.group(1)) if match else 0


def _cleanup_render_files(render_dir: Path) -> None:
    for leftover in render_dir.glob("page-*.png"):
        try:
            leftover.unlink()
        except OSError:
            pass


def pdf_ingest(
    pdf_path: Path | str,
    output_root: Optional[Path] = None,
    dpi: int = 150,
    copy_source: bool = True,
    cancel: Optional[Callable[[], bool]] = None,
    cancel_file: Optional[str] = None,
) -> PdfIngestResult:
    source = Path(pdf_path)
    if not source.exists():
        raise FileNotFoundError(f"PDF not found: {source}")

    pdftoppm = _ensure_pdftoppm()
    if not pdftoppm:
        raise RuntimeError(
            "pdftoppm not found. Install Poppler (pdftoppm) to render PDF pages."
        )

    doc_id = _generate_doc_id(source.stem)
    repo = repo_root()
    out_root = Path(output_root) if output_root else pdf_output_root()
    output_dir = out_root / doc_id
    pages_dir = output_dir / "pages"
    pages_dir.mkdir(parents=True, exist_ok=True)

    cancel_ctx = CancelContext(cancel=cancel, cancel_file=cancel_file)
    if cancel_ctx.requested():
        raise CancelledError("canceled")

    prefix = pages_dir / "page"
    proc = subprocess.Popen(
        [pdftoppm, "-png", "-r", str(dpi), str(source), str(prefix)],
        cwd=repo,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.PIPE,
        text=True,
        encoding="utf-8",
        errors="replace",
    )

    stderr_text = ""
    while True:
        if cancel_ctx.requested():
            try:
                proc.terminate()
            except Exception:  # noqa: BLE001
                pass
            try:
                proc.wait(timeout=2)
            except Exception:  # noqa: BLE001
                pass
            if os.name == "nt":
                try:
                    subprocess.run(
                        ["taskkill", "/F", "/T", "/PID", str(proc.pid)],
                        capture_output=True,
                        text=True,
                        encoding="utf-8",
                        errors="replace",
                    )
                except Exception:  # noqa: BLE001
                    pass
            _cleanup_render_files(pages_dir)
            raise CancelledError("canceled")

        ret = proc.poll()
        if ret is not None:
            if proc.stderr is not None:
                try:
                    stderr_text = proc.stderr.read().strip()
                except OSError:
                    stderr_text = ""
            if int(ret) != 0:
                _cleanup_render_files(pages_dir)
                raise RuntimeError(f"pdftoppm failed (exit {ret}): {stderr_text}")
            break
        time.sleep(0.2)

    page_files = sorted(pages_dir.glob("page-*.png"), key=_page_sort_key)
    if not page_files:
        raise RuntimeError("No PNG pages generated by pdftoppm")

    pages: List[PdfPage] = []
    for idx, src in enumerate(page_files, start=1):
        target = pages_dir / f"page_{idx:04d}.png"
        src.replace(target)
        width, height = _png_size(target)
        pages.append(
            PdfPage(
                page=idx,
                png_path=str(target.relative_to(output_dir).as_posix()),
                width=width,
                height=height,
            )
        )

    source_copy_path = ""
    if copy_source:
        copied_source = output_dir / source.name
        try:
            same_path = source.resolve() == copied_source.resolve()
        except OSError:
            same_path = False
        if not same_path:
            shutil.copy2(source, copied_source)
        source_copy_path = copied_source.relative_to(output_dir).as_posix()

    # Store repo-relative source path for portability (so other checkouts don't leak absolute paths).
    try:
        src_abs = source.resolve()
    except OSError:
        src_abs = source
    try:
        source_ptr = src_abs.relative_to(repo.resolve()).as_posix()
    except Exception:  # noqa: BLE001
        source_ptr = str(src_abs)

    manifest = {
        "doc_id": doc_id,
        "source_path": str(source_ptr),
        "created_at": _now_iso(),
        "page_count": len(pages),
        "source_copy_path": source_copy_path,
        "pages": [page.__dict__ for page in pages],
    }

    output_dir.mkdir(parents=True, exist_ok=True)
    manifest_path = write_manifest(output_dir, manifest)

    return PdfIngestResult(
        doc_id=doc_id,
        output_dir=str(output_dir),
        manifest_path=str(manifest_path),
        pages=pages,
    )
